# Generated by Django 5.0.6 on 2024-06-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('zodiac', models.CharField(blank=True, choices=[('Aries', 'Овен'), ('Taurus', 'Телец'), ('Gemini', 'Близнецы'), ('Cancer', 'Рак'), ('Leo', 'Лев'), ('Virgo', 'Дева'), ('Libra', 'Весы'), ('Scorpio', 'Скорпион'), ('Ophiuchus', 'Змееносец'), ('Sagittarius', 'Стрелец'), ('Capricorn', 'Козерог'), ('Aquarius', 'Водолей'), ('Pisces', 'Рыбы')], max_length=20, verbose_name='Знак зодиака')),
                ('gender', models.CharField(blank=True, choices=[('man', 'Мужчина'), ('woman', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.FileField(blank=True, null=True, upload_to='users/', verbose_name='Фотография')),
                ('telegram', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ник в телеграме')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
